language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew clean test -Pbuild=dev

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
