language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

script:
    - ./gradlew clean test

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
