language: android

android:
  components:
    - platform-tools
    - tools 
    - build-tools-30.0.3
    - android-30
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew clean test -Pbuild=dev

notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-30"

cache:
  directories:
    - $HOME/.gradle
