name: Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3.0.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle 
        run: ./gradlew clean test -Pbuild=dev
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: App
          path: ./app/app-release.apk
